### ISSUE TITLE
Bug in Automaton.get_shortest_path when reading dot models and using learning algorithm

### ISSUE THREAD

**Issue by MDrey101** [DES-Lab/AALpy#20]
When reading in a dot model and using it with a learning algorithm, an error occurs stating "'list' object has no attribute 'transitions'".
The error occurs when I try to read in a dot model with automaton_type set to onfsm and using it with run_non_det_Lstar or run_stochastic_Lstar (at least I tried those).

I temporarily fixed it by adding the automaton_type as parameter to get_shortest_path and check the method for the onfsm type:
>    while queue:
>        path = queue.pop(0)
>            if automaton_type is not None and automaton_type == "onfsm":
>                node = path[0]
>            else:
>                node = path[-1]
>      . . .

This circumvents the problem, since the path variable, at some point, has the automaton state at index 0 and a tuple at index 1.

**Comment by emuskardin** [comment]
Hi,
thanks for the notice.
"Problem" that will be solved in near feature is that some of the methods of some classes, like `get_shortest_path` only work (for now) on deterministic automata. Either I need to implement for non-det and stochastic automata, or restrict it so that you cannot call it from other formalism aside from DFA, Mealy, Moore.

**Comment by emuskardin** [comment]
Hey,
I solved the issue. Compute shortest path is now only available for deterministic automaton. If you still need the function, I suggest that you create subclass NondeterministicAutomaton and implement `get_shortest_path` there. That way, there is a separation of what methods are available for determininistic, non-deterministic, and stochastic models
